services:
  - type: web
    name: assignease
    runtime: python
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn assignease.wsgi:application"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
