# Generated by Django 4.0.4 on 2026-06-15 01:45

from django.db import migrations
from django.contrib.auth.models import User


def create_initial_data(apps, schema_editor):
    """Create initial admin user and sample data"""
    Department = apps.get_model('main', 'Department')
    Faculty = apps.get_model('main', 'Faculty')
    Student = apps.get_model('main', 'Student')
    Course = apps.get_model('main', 'Course')
    
    # Create superuser if not exists
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser(
            username='admin',
            email='admin@assignease.com',
            password='admin123'
        )
        print('✅ Admin user created: admin/admin123')
    
    # Create sample department
    if not Department.objects.exists():
        dept = Department.objects.create(
            department_id='CS',
            name='Computer Science'
        )
        print(f'✅ Department created: {dept.name}')
        
        # Create faculty
        faculty = Faculty.objects.create(
            faculty_id='1001',
            name='Dr. John Smith',
            department=dept,
            email='faculty@example.com',
            password='faculty123'
        )
        print(f'✅ Faculty created: ID 1001, password faculty123')
        
        # Create student
        student = Student.objects.create(
            student_id='2001',
            name='Jane Doe',
            department=dept,
            email='student@example.com',
            password='student123'
        )
        print(f'✅ Student created: ID 2001, password student123')
        
        # Create course
        course = Course.objects.create(
            code='CS101',
            name='Introduction to Computer Science',
            department=dept,
            faculty=faculty,
            studentKey=1234,
            facultyKey=5678
        )
        course.student.add(student)
        print(f'✅ Course created: CS101')
        print('🎉 Initial data setup complete!')


def delete_initial_data(apps, schema_editor):
    """Reverse migration - delete sample data"""
    Department = apps.get_model('main', 'Department')
    Faculty = apps.get_model('main', 'Faculty')
    Student = apps.get_model('main', 'Student')
    Course = apps.get_model('main', 'Course')
    
    Course.objects.filter(code='CS101').delete()
    Student.objects.filter(student_id='2001').delete()
    Faculty.objects.filter(faculty_id='1001').delete()
    Department.objects.filter(department_id='CS').delete()
    User.objects.filter(username='admin').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data, delete_initial_data),
    ]
